### ISSUE TITLE
How to add the parameters -f, -e, -n

### ISSUE THREAD

**Issue by mf093087** [aljoshakoecher/plc2skill#4]
Currently, I have a plcopen XML format, I am following your guidance to execute the mapping operations. I am using Intellij as the IDE. here is the environment paprameter I use

-f=D:\PLC automatic generation\PLC code -e=opc.tcp://localhost:4840 -n=D:\PLC automatic generation\PLC code

However, when I run the main function, I receive this error, could you please help me?
![image](https://user-images.githubusercontent.com/67538561/189889160-62d81d93-02c2-4206-a5a9-6d2cef8f65ef.png)

**Comment by aljoshakoecher** [comment]
Hey @mf093087, you shouldn't use "=" with CLI parameters, so please try it just like this:
`java -jar cli-x.x.x-jar -f <PLCopen XML file you want to map> -e <endpointURL of your PLC> -n <root component of the PLC project>`.  You can also try to wrap your parameters in quotation marks to be sure to not have problems (e.g. when your parameters have spaces) 

Currently, all these parameters are required:
- `-f` is the file you want to map (looks good in your example)
- `-e` is the endpoint of the OPC UA server, which is unfortunately not included in a PLCopen XML file (looks good in your example)
- `n` is a root component of a node ID. We used Codesys to write the PLC code and generate the PLCopen XML. Codesys automatically generates node IDs based on the project structure AND a constant root component. Unfortunately, this root part of a node ID is not preserved in the PLCopen XML and thus has to be added with this parameter. You can check your OPC UA server with a client such as UaExpert. I just checked for an example server and found this node ID `ns=4;s=|var|CODESYS Control Win V3 x64.Application.PLC_PRG.sensorA`. The PLCopen XML contains the structure starting with Application, so in this case you would have to set -n to "ns=4;s=|var|CODESYS Control Win V3 x64".

I have to admint , this parameter is currently a problematic one, because it is error-prone to set and may also be different / not suitable depending on the tool used to generate the PLCopen XML file. Could be that other create a completely different node ID structure and all our assumptions are invalid. We are currently working on simplifying this aspect.

Hope that helps!

**Comment by aljoshakoecher** [comment]
Hey @mf093087, I have some good news for you. Using Plc2Skill is now much easier because you don't have to pass in the `-n` parameter anymore. Only `-f` and `-e` are required if the PLC and its OPC UA server are running. Plc2Skill will then automatically browse for variables and resolve their nodeIds.

**Comment by aljoshakoecher** [comment]
You can also pass in a user and password in case the OPC UA server requires an authenticated login.
And in cases where this new logic fails you can still fall back to the "old way" and add a root component of the nodeId manually by passing in `-n`. Please check out the updated documentation, the latest release is now properly released [here](https://github.com/aljoshakoecher/plc2skill/releases/tag/v0.1.0).

Let me know if you can work with that 😄

**Comment by aljoshakoecher** [comment]
Closing this for now. Feel free to reopen or create a new issue in case you have any questions.
